load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "sram_c",
    srcs = ["sram.cpp"],
    hdrs = ["sram.hpp"],
    deps = [],
    includes = ["."],
    visibility = ["//visibility:public"],
)

