load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "elf_loader",
    srcs = ["elf_loader.cpp"],
    hdrs = ["elf_loader.hpp"],
    deps = [],
    includes = ["."],
    visibility = ["//visibility:public"],
)

