#!/usr/bin/env python3

"""

"""

import argparse

from commander import *

def parse_args():
  parser = argparse.ArgumentParser(
    description='Argument parser for pyrun.')

  parser.add_argument(
    'target',
    help='Build & run target.')

  parser.add_argument(
    '-v', '--verbose',
    action='store_true',
    help='Enable verbose output.')

  args = parser.parse_args()
  return args

def main():
  # Start up message
  print("pyrun")

  # Argument parsing
  args = parse_args()
  print(args)

  # Run build if not skipped
  cmder = commander()
  cmder.set_cmd(f"bazel build {args.target}")
  ret = cmder.run()
  if ret:
    print(cmder.get_error())
    return ret
  else:
    print(cmder.get_output())

  # Run test
  binary = "bazel-bin/"+args.target[2:].replace(':', '/', 1)
  cmder.__init__()
  cmder.set_cmd(binary)
  ret = cmder.run()
  if ret:
    print(cmder.get_error())
    return ret
  else:
    print(cmder.get_output())

  return 0

if __name__=="__main__":
  main()

